################ English language ##################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

################ French Language ###################
[fr]
languageName = "Français"
languageCode = "fr-Fr"
contentDir = "content/french"
weight = 1
