############# French navigation ##############

# main menu
[[main]]
name = "Acceuil"
url = "/"
weight = 1

[[main]]
name = "À propos"
url = "about/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
name = "Auteurs"
url = "authors/"
weight = 4

[[main]]
name = "Catégories"
url = "categories/"
weight = 5

# footer menu
[[footer]]
name = "À propos"
url = "about/"
weight = 1

[[footer]]
name = "Politique de confidentialité"
url = "privacy-policy/"
weight = 2
