############# French navigation ##############

# main menu
[[main]]
name = "Acceuil"
url = "/"
weight = 1

[[main]]
name = "À propos"
url = "about/"
weight = 2

[[main]]
weight = 3
name = "Pages"
hasChildren = true

[[main]]
parent = "Pages"
name = "Blog"
url = "blog/"

[[main]]
parent = "Pages"
name = "Contact"
url = "contact/"

[[main]]
parent = "Pages"
name = "Auteurs"
url = "authors/"

[[main]]
parent = "Pages"
name = "Catégories"
url = "categories/"

# footer menu
[[footer]]
name = "À propos"
url = "about/"
weight = 1

[[footer]]
name = "Politique de confidentialité"
url = "privacy-policy/"
weight = 2
